// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJa-GIfLj6maQhNvG9LbZSWN761KByhiI',
    appId: '1:135440579731:web:3420866c36b040a972a166',
    messagingSenderId: '135440579731',
    projectId: 'dechonker',
    authDomain: 'dechonker.firebaseapp.com',
    storageBucket: 'dechonker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqTSKoW0Et1J1l0D7HsCH4umXHRp_SoG4',
    appId: '1:135440579731:android:0b2997967509ec5e72a166',
    messagingSenderId: '135440579731',
    projectId: 'dechonker',
    storageBucket: 'dechonker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUnCm2taV0QvEO4NAoK6pQgFcxX8ifPG0',
    appId: '1:135440579731:ios:ab789f72117bba7472a166',
    messagingSenderId: '135440579731',
    projectId: 'dechonker',
    storageBucket: 'dechonker.appspot.com',
    iosBundleId: 'com.example.deChonked',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUnCm2taV0QvEO4NAoK6pQgFcxX8ifPG0',
    appId: '1:135440579731:ios:0db570e41c52112b72a166',
    messagingSenderId: '135440579731',
    projectId: 'dechonker',
    storageBucket: 'dechonker.appspot.com',
    iosBundleId: 'com.example.deChonked.RunnerTests',
  );
}
